package pallette.general;

abstract enum StrColours( String ) to String from String {
    var AliceBlue:  	        '#F0F8FF';
    var AntiqueWhite:          '#FAEBD7';
    var Aqua:  	            '#00FFFF';
    var Aquamarine:            '#7FFFD4';
    var Azure:  	            '#F0FFFF';
    var Beige:                 '#F5F5DC';
    var Bisque:      	        '#FFE4C4';
    var Black:                 '#000000';
    var BlanchedAlmond:        '#FFEBCD';
    var Blue:                  '#0000FF';
    var BlueViolet:       	    '#8A2BE2';
    var Brown:           	    '#A52A2A';
    var BurlyWood:       	    '#DEB887';
    var CadetBlue:       	    '#5F9EA0';
    var Chartreuse:      	    '#7FFF00';
    var Chocolate:       	    '#D2691E';
    var Coral:           	    '#FF7F50';
    var CornflowerBlue:  	    '#6495ED';
    var Cornsilk:  	        '#FFF8DC';
    var Crimson:         	    '#DC143C';
    var Cyan:            	    '#00FFFF';
    var DarkBlue:        	    '#00008B';
    var DarkCyan:        	    '#008B8B';
    var DarkGoldenRod:  	    '#B8860B';
    var DarkGray:      	    '#A9A9A9';
    var DarkGrey:      	    '#A9A9A9';
    var DarkGreen:     	    '#006400';
    var DarkKhaki:       	    '#BDB76B';
    var DarkMagenta:     	    '#8B008B';
    var DarkOliveGreen: 	    '#556B2F';
    var Darkorange:     	    '#FF8C00';
    var DarkOrchid:      	    '#9932CC';
    var DarkRed:         	    '#8B0000';
    var DarkSalmon:      	    '#E9967A';
    var DarkSeaGreen:    	    '#8FBC8F';
    var DarkSlateBlue:  	    '#483D8B';
    var DarkSlateGray:  	    '#2F4F4F';
    var DarkSlateGrey:  	    '#2F4F4F';
    var DarkTurquoise:  	    '#00CED1';
    var DarkViolet:      	    '#9400D3';
    var DeepPink:        	    '#FF1493';
    var DeepSkyBlue:     	    '#00BFFF';
    var DimGray:         	    '#696969';
    var DimGrey:         	    '#696969';
    var DodgerBlue:      	    '#1E90FF';
    var FireBrick:       	    '#B22222';
    var FloralWhite:     	    '#FFFAF0';
    var ForestGreen:     	    '#228B22';
    var Fuchsia:         	    '#FF00FF';
    var Gainsboro:       	    '#DCDCDC';
    var GhostWhite:      	    '#F8F8FF';
    var Gold:            	    '#FFD700';
    var GoldenRod:       	    '#DAA520';
    var Gray:  	            '#808080';
    var Grey:  	            '#808080';
    var Green:  	            '#008000';
    var GreenYellow:  	        '#ADFF2F';
    var HoneyDew:  	        '#F0FFF0';
    var HotPink:  	            '#FF69B4';
    var IndianRed:   	        '#CD5C5C';
    var Indigo:   	            '#4B0082';
    var Ivory:  	            '#FFFFF0';
    var Khaki:  	            '#F0E68C';
    var Lavender:  	        '#E6E6FA';
    var LavenderBlush:  	    '#FFF0F5';
    var LawnGreen:  	        '#7CFC00';
    var LemonChiffon:  	    '#FFFACD';
    var LightBlue:  	        '#ADD8E6';
    var LightCoral:  	        '#F08080';
    var LightCyan:  	        '#E0FFFF';
    var LightGoldenRodYellow:  '#FAFAD2';
    var LightGray:  	        '#D3D3D3';
    var LightGrey:  	        '#D3D3D3';
    var LightGreen:  	        '#90EE90';
    var LightPink:  	        '#FFB6C1';
    var LightSalmon:  	        '#FFA07A';
    var LightSeaGreen:  	    '#20B2AA';
    var LightSkyBlue:          '#87CEFA';
    var LightSlateGray:  	    '#778899';
    var LightSlateGrey:  	    '#778899';
    var LightSteelBlue:  	    '#B0C4DE';
    var LightYellow:  	        '#FFFFE0';
    var Lime:               	'#00FF00';
    var LimeGreen:             '#32CD32';
    var Linen:               	'#FAF0E6';
    var Magenta:             	'#FF00FF';
    var Maroon:              	'#800000';
    var MediumAquaMarine:    	'#66CDAA';
    var MediumBlue:          	'#0000CD';
    var MediumOrchid:        	'#BA55D3';
    var MediumPurple:        	'#9370DB';
    var MediumSeaGreen:      	'#3CB371';
    var MediumSlateBlue:     	'#7B68EE';
    var MediumSpringGreen:  	'#00FA9A';
    var MediumTurquoise:     	'#48D1CC';
    var MediumVioletRed:     	'#C71585';
    var MidnightBlue:        	'#191970';
    var MintCream:           	'#F5FFFA';
    var MistyRose:           	'#FFE4E1';
    var Moccasin:            	'#FFE4B5';
    var NavajoWhite:         	'#FFDEAD';
    var Navy:                	'#000080';
    var OldLace:             	'#FDF5E6';
    var Olive:               	'#808000';
    var OliveDrab:           	'#6B8E23';
    var Orange:              	'#FFA500';
    var OrangeRed:           	'#FF4500';
    var Orchid:              	'#DA70D6';
    var PaleGoldenRod:       	'#EEE8AA';
    var PaleGreen:           	'#98FB98';
    var PaleTurquoise:       	'#AFEEEE';
    var PaleVioletRed:       	'#DB7093';
    var PapayaWhip:          	'#FFEFD5';
    var PeachPuff:           	'#FFDAB9';
    var Peru:                	'#CD853F';
    var Pink:                	'#FFC0CB';
    var Plum:                	'#DDA0DD';
    var PowderBlue:          	'#B0E0E6';
    var Purple:              	'#800080';
    var Red:                 	'#FF0000';
    var RosyBrown:           	'#BC8F8F';
    var RoyalBlue:           	'#4169E1';
    var SaddleBrown:         	'#8B4513';
    var Salmon:              	'#FA8072';
    var SandyBrown:          	'#F4A460';
    var SeaGreen:            	'#2E8B57';
    var SeaShell:            	'#FFF5EE';
    var Sienna:              	'#A0522D';
    var Silver:              	'#C0C0C0';
    var SkyBlue:             	'#87CEEB';
    var SlateBlue:           	'#6A5ACD';
    var SlateGray:           	'#708090';
    var SlateGrey:           	'#708090';
    var Snow:                	'#FFFAFA';
    var SpringGreen:         	'#00FF7F';
    var SteelBlue:           	'#4682B4';
    var Tan:                 	'#D2B48C';
    var Teal:                	'#008080';
    var Thistle:             	'#D8BFD8';
    var Tomato:              	'#FF6347';
    var Turquoise:           	'#40E0D0';
    var Violet:              	'#EE82EE';
    var Wheat:               	'#F5DEB3';
    var White:               	'#FFFFFF';
    var WhiteSmoke:          	'#F5F5F5';
    var Yellow:              	'#FFFF00';
    var YellowGreen: 	        '#9ACD32';
	}
  
class BrowserColours {
	static inline public function rgb( color: StrColours ): Array<Int>
	{
	    return switch( color )
	    {
            case AliceBlue:  	        [ 0xF0, 0xF8, 0xFF ];
            case AntiqueWhite:          [ 0xFA, 0xEB, 0xD7 ];
            case Aqua:  	            [ 0x00, 0xFF, 0xFF ];
            case Aquamarine:            [ 0x7F, 0xFF, 0xD4 ];
            case Azure:  	            [ 0xF0, 0xFF, 0xFF ];
            case Beige:                 [ 0xF5, 0xF5, 0xDC ];
            case Bisque:      	        [ 0xFF, 0xE4, 0xC4 ];
            case Black:                 [ 0x00, 0x00, 0x00 ];
            case BlanchedAlmond:        [ 0xFF, 0xEB, 0xCD ];
            case Blue:                  [ 0x00, 0x00, 0xFF ];
            case BlueViolet:       	    [ 0x8A, 0x2B, 0xE2 ];
            case Brown:           	    [ 0xA5, 0x2A, 0x2A ];
            case BurlyWood:       	    [ 0xDE, 0xB8, 0x87 ];
            case CadetBlue:       	    [ 0x5F, 0x9E, 0xA0 ];
            case Chartreuse:      	    [ 0x7F, 0xFF, 0x00 ];
            case Chocolate:       	    [ 0xD2, 0x69, 0x1E ];
            case Coral:           	    [ 0xFF, 0x7F, 0x50 ];
            case CornflowerBlue:  	    [ 0x64, 0x95, 0xED ];
            case Cornsilk:  	        [ 0xFF, 0xF8, 0xDC ];
            case Crimson:         	    [ 0xDC, 0x14, 0x3C ];
            case Cyan:            	    [ 0x00, 0xFF, 0xFF ];
            case DarkBlue:        	    [ 0x00, 0x00, 0x8B ];
            case DarkCyan:        	    [ 0x00, 0x8B, 0x8B ];
            case DarkGoldenRod:  	    [ 0xB8, 0x86, 0x0B ];
            case DarkGray:      	    [ 0xA9, 0xA9, 0xA9 ];
            case DarkGrey:      	    [ 0xA9, 0xA9, 0xA9 ];
            case DarkGreen:     	    [ 0x00, 0x64, 0x00 ];
            case DarkKhaki:       	    [ 0xBD, 0xB7, 0x6B ];
            case DarkMagenta:     	    [ 0x8B, 0x00, 0x8B ];
            case DarkOliveGreen: 	    [ 0x55, 0x6B, 0x2F ];
            case Darkorange:     	    [ 0xFF, 0x8C, 0x00 ];
            case DarkOrchid:      	    [ 0x99, 0x32, 0xCC ];
            case DarkRed:         	    [ 0x8B, 0x00, 0x00 ];
            case DarkSalmon:      	    [ 0xE9, 0x96, 0x7A ];
            case DarkSeaGreen:    	    [ 0x8F, 0xBC, 0x8F ];
            case DarkSlateBlue:  	    [ 0x48, 0x3D, 0x8B ];
            case DarkSlateGray:  	    [ 0x2F, 0x4F, 0x4F ];
            case DarkSlateGrey:  	    [ 0x2F, 0x4F, 0x4F ];
            case DarkTurquoise:  	    [ 0x00, 0xCE, 0xD1 ];
            case DarkViolet:      	    [ 0x94, 0x00, 0xD3 ];
            case DeepPink:        	    [ 0xFF, 0x14, 0x93 ];
            case DeepSkyBlue:     	    [ 0x00, 0xBF, 0xFF ];
            case DimGray:         	    [ 0x69, 0x69, 0x69 ];
            case DimGrey:         	    [ 0x69, 0x69, 0x69 ];
            case DodgerBlue:      	    [ 0x1E, 0x90, 0xFF ];
            case FireBrick:       	    [ 0xB2, 0x22, 0x22 ];
            case FloralWhite:     	    [ 0xFF, 0xFA, 0xF0 ];
            case ForestGreen:     	    [ 0x22, 0x8B, 0x22 ];
            case Fuchsia:         	    [ 0xFF, 0x00, 0xFF ];
            case Gainsboro:       	    [ 0xDC, 0xDC, 0xDC ];
            case GhostWhite:      	    [ 0xF8, 0xF8, 0xFF ];
            case Gold:            	    [ 0xFF, 0xD7, 0x00 ];
            case GoldenRod:       	    [ 0xDA, 0xA5, 0x20 ];
            case Gray:  	            [ 0x80, 0x80, 0x80 ];
            case Grey:  	            [ 0x80, 0x80, 0x80 ];
            case Green:  	            [ 0x00, 0x80, 0x00 ];
            case GreenYellow:  	        [ 0xAD, 0xFF, 0x2F ];
            case HoneyDew:  	        [ 0xF0, 0xFF, 0xF0 ];
            case HotPink:  	            [ 0xFF, 0x69, 0xB4 ];
            case IndianRed:   	        [ 0xCD, 0x5C, 0x5C ];
            case Indigo:   	            [ 0x4B, 0x00, 0x82 ];
            case Ivory:  	            [ 0xFF, 0xFF, 0xF0 ];
            case Khaki:  	            [ 0xF0, 0xE6, 0x8C ];
            case Lavender:  	        [ 0xE6, 0xE6, 0xFA ];
            case LavenderBlush:  	    [ 0xFF, 0xF0, 0xF5 ];
            case LawnGreen:  	        [ 0x7C, 0xFC, 0x00 ];
            case LemonChiffon:  	    [ 0xFF, 0xFA, 0xCD ];
            case LightBlue:  	        [ 0xAD, 0xD8, 0xE6 ];
            case LightCoral:  	        [ 0xF0, 0x80, 0x80 ];
            case LightCyan:  	        [ 0xE0, 0xFF, 0xFF ];
            case LightGoldenRodYellow:  [ 0xFA, 0xFA, 0xD2 ];
            case LightGray:  	        [ 0xD3, 0xD3, 0xD3 ];
            case LightGrey:  	        [ 0xD3, 0xD3, 0xD3 ];
            case LightGreen:  	        [ 0x90, 0xEE, 0x90 ];
            case LightPink:  	        [ 0xFF, 0xB6, 0xC1 ];
            case LightSalmon:  	        [ 0xFF, 0xA0, 0x7A ];
            case LightSeaGreen:  	    [ 0x20, 0xB2, 0xAA ];
            case LightSkyBlue:          [ 0x87, 0xCE, 0xFA ];
            case LightSlateGray:  	    [ 0x77, 0x88, 0x99 ];
            case LightSlateGrey:  	    [ 0x77, 0x88, 0x99 ];
            case LightSteelBlue:  	    [ 0xB0, 0xC4, 0xDE ];
            case LightYellow:  	        [ 0xFF, 0xFF, 0xE0 ];
            case Lime:               	[ 0x00, 0xFF, 0x00 ];
            case LimeGreen:             [ 0x32, 0xCD, 0x32 ];
            case Linen:               	[ 0xFA, 0xF0, 0xE6 ];
            case Magenta:             	[ 0xFF, 0x00, 0xFF ];
            case Maroon:              	[ 0x80, 0x00, 0x00 ];
            case MediumAquaMarine:    	[ 0x66, 0xCD, 0xAA ];
            case MediumBlue:          	[ 0x00, 0x00, 0xCD ];
            case MediumOrchid:        	[ 0xBA, 0x55, 0xD3 ];
            case MediumPurple:        	[ 0x93, 0x70, 0xDB ];
            case MediumSeaGreen:      	[ 0x3C, 0xB3, 0x71 ];
            case MediumSlateBlue:     	[ 0x7B, 0x68, 0xEE ];
            case MediumSpringGreen:  	[ 0x00, 0xFA, 0x9A ];
            case MediumTurquoise:     	[ 0x48, 0xD1, 0xCC ];
            case MediumVioletRed:     	[ 0xC7, 0x15, 0x85 ];
            case MidnightBlue:        	[ 0x19, 0x19, 0x70 ];
            case MintCream:           	[ 0xF5, 0xFF, 0xFA ];
            case MistyRose:           	[ 0xFF, 0xE4, 0xE1 ];
            case Moccasin:            	[ 0xFF, 0xE4, 0xB5 ];
            case NavajoWhite:         	[ 0xFF, 0xDE, 0xAD ];
            case Navy:                	[ 0x00, 0x00, 0x80 ];
            case OldLace:             	[ 0xFD, 0xF5, 0xE6 ];
            case Olive:               	[ 0x80, 0x80, 0x00 ];
            case OliveDrab:           	[ 0x6B, 0x8E, 0x23 ];
            case Orange:              	[ 0xFF, 0xA5, 0x00 ];
            case OrangeRed:           	[ 0xFF, 0x45, 0x00 ];
            case Orchid:              	[ 0xDA, 0x70, 0xD6 ];
            case PaleGoldenRod:       	[ 0xEE, 0xE8, 0xAA ];
            case PaleGreen:           	[ 0x98, 0xFB, 0x98 ];
            case PaleTurquoise:       	[ 0xAF, 0xEE, 0xEE ];
            case PaleVioletRed:       	[ 0xDB, 0x70, 0x93 ];
            case PapayaWhip:          	[ 0xFF, 0xEF, 0xD5 ];
            case PeachPuff:           	[ 0xFF, 0xDA, 0xB9 ];
            case Peru:                	[ 0xCD, 0x85, 0x3F ];
            case Pink:                	[ 0xFF, 0xC0, 0xCB ];
            case Plum:                	[ 0xDD, 0xA0, 0xDD ];
            case PowderBlue:          	[ 0xB0, 0xE0, 0xE6 ];
            case Purple:              	[ 0x80, 0x00, 0x80 ];
            case Red:                 	[ 0xFF, 0x00, 0x00 ];
            case RosyBrown:           	[ 0xBC, 0x8F, 0x8F ];
            case RoyalBlue:           	[ 0x41, 0x69, 0xE1 ];
            case SaddleBrown:         	[ 0x8B, 0x45, 0x13 ];
            case Salmon:              	[ 0xFA, 0x80, 0x72 ];
            case SandyBrown:          	[ 0xF4, 0xA4, 0x60 ];
            case SeaGreen:            	[ 0x2E, 0x8B, 0x57 ];
            case SeaShell:            	[ 0xFF, 0xF5, 0xEE ];
            case Sienna:              	[ 0xA0, 0x52, 0x2D ];
            case Silver:              	[ 0xC0, 0xC0, 0xC0 ];
            case SkyBlue:             	[ 0x87, 0xCE, 0xEB ];
            case SlateBlue:           	[ 0x6A, 0x5A, 0xCD ];
            case SlateGray:           	[ 0x70, 0x80, 0x90 ];
            case SlateGrey:           	[ 0x70, 0x80, 0x90 ];
            case Snow:                	[ 0xFF, 0xFA, 0xFA ];
            case SpringGreen:         	[ 0x00, 0xFF, 0x7F ];
            case SteelBlue:           	[ 0x46, 0x82, 0xB4 ];
            case Tan:                 	[ 0xD2, 0xB4, 0x8C ];
            case Teal:                	[ 0x00, 0x80, 0x80 ];
            case Thistle:             	[ 0xD8, 0xBF, 0xD8 ];
            case Tomato:              	[ 0xFF, 0x63, 0x47 ];
            case Turquoise:           	[ 0x40, 0xE0, 0xD0 ];
            case Violet:              	[ 0xEE, 0x82, 0xEE ];
            case Wheat:               	[ 0xF5, 0xDE, 0xB3 ];
            case White:               	[ 0xFF, 0xFF, 0xFF ];
            case WhiteSmoke:          	[ 0xF5, 0xF5, 0xF5 ];
            case Yellow:              	[ 0xFF, 0xFF, 0x00 ];
            case YellowGreen: 	        [ 0x9A, 0xCD, 0x32 ];   
	    }
 }
